spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rc?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
  thymeleaf:
    cache: false
  jackson:
          date-format: yyyy-MM-dd
          time-zone: GMT+8
#邮箱发送验证码的配置
  mail:
#QQ邮箱服务器
    host: smtp.qq.com
#发送邮件的账户
    username: 1610424323@qq.com
#QQ邮箱第三方授权码
    password: zugkfowfzysgijjf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    port: 465
mybatis:
  type-aliases-package: guet.hxm.rc.entity
  mapper-locations: classpath:mapper/*.xml
#pagehelper配置信息
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  config: classpath:logback.xml
server:
  port: 8080
  servlet:
    context-path: /rc
fileRootPath: http://localhost:8080/rc
